# Generated by Django 4.2.16 on 2024-11-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_handler', '0002_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='processeddata',
            name='is_matched',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='commission',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='difference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='guest_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='rate_amd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
