# Generated by Django 4.2.16 on 2024-11-20 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_handler', '0003_processeddata_is_matched_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrivalTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_merged', models.BooleanField(blank=True, default=False, null=True)),
                ('arr_date_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dept_date_name', models.CharField(blank=True, max_length=255, null=True)),
                ('arr_dept_date_name', models.CharField(blank=True, max_length=255, null=True)),
                ('rate_amt_name_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VendorTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(blank=True, max_length=255, null=True)),
                ('guest_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_merged', models.BooleanField(blank=True, default=False, null=True)),
                ('arr_date_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dept_date_name', models.CharField(blank=True, max_length=255, null=True)),
                ('arr_dept_date_name', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='is_matched',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
